% Run this after the G2S server is up and the MATLAB interface is compiled.

fprintf('warning probe\n');
result = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'warning', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-showLogs', ...
    '-returnFormat', 'schema');
disp(['warning probe job id: ', num2str(result.job_id)]);
disp(['warning probe elapsed seconds: ', num2str(result.time)]);
disp(result);

fprintf('\nerror probe\n');
submitResult = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'error', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-submitOnly', ...
    '-returnFormat', 'schema');
jobId = submitResult.job_id;
disp(['error probe job id: ', num2str(jobId)]);
g2s('-waitAndDownload', jobId, '-returnFormat', 'schema');
