% Run this after the G2S server is up and the MATLAB interface is compiled.

fprintf('warning probe\n');
[elapsed, meta, jobId] = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'warning', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-showLogs', ...
    '-returnMeta');
disp(['warning probe job id: ', num2str(jobId)]);
disp(['warning probe elapsed seconds: ', num2str(elapsed)]);
disp(meta);

fprintf('\nerror probe\n');
jobId = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'error', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-submitOnly');
disp(['error probe job id: ', num2str(jobId)]);
g2s('-waitAndDownload', jobId, '-returnMeta');
