ti = single(imread('https://raw.githubusercontent.com/GAIA-UNIL/TrainingImagesTIFF/master/stone.tiff'));

result = g2s( ...
    '-a', 'autoQS', ...
    '-ti', ti, ...
    '-dt', [0], ...
    '-n', 40, ...
    '-k', 1.2, ...
    '-j', 0.5);

disp(['job ', num2str(result.job_id)]);
disp(size(result.mean_error));
disp(size(result.deviation_error));
disp(size(result.sample_count));
