% Run this after the G2S server is up and the MATLAB interface is compiled.

fprintf('warning probe\n');
schemaResult = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'warning', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-showLogs');
elapsed = schemaResult.time;
disp(['warning probe elapsed seconds: ', num2str(elapsed)]);

fprintf('\nerror probe\n');
schemaResult = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'error', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-submitOnly');
jobId = schemaResult.job_id;
disp(['error probe job id: ', num2str(jobId)]);
g2s('-waitAndDownload', jobId);
