warning_result = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'warning', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-showLogs');

disp(['warning probe ', num2str(warning_result.job_id), ' ', warning_result.status]);
disp(warning_result.artifacts);

submitted = g2s( ...
    '-a', 'report_probe', ...
    '-mode', 'error', ...
    '-steps', 5, ...
    '-sleepMs', 120, ...
    '-submitOnly');

disp(['submitted error probe ', num2str(submitted.job_id)]);
g2s('-waitAndDownload', submitted.job_id);
