ti = single(imread('https://raw.githubusercontent.com/GAIA-UNIL/TrainingImagesTIFF/master/stone.tiff'));

result = g2s( ...
    '-a', 'ds', ...
    '-ti', ti, ...
    '-di', single(nan(size(ti))), ...
    '-dt', [0], ...
    '-th', 0.05, ...
    '-f', 0.30, ...
    '-n', 30, ...
    '-s', 100, ...
    '-j', 1.00001);

disp(['job ', num2str(result.job_id), ', seconds ', num2str(result.time)]);
disp(size(result.simulation));
disp(size(result.indexmap));
