ti = single(imread('https://raw.githubusercontent.com/GAIA-UNIL/TrainingImagesTIFF/master/Strebelle.tiff'));

result = g2s( ...
    '-a', 'snesim', ...
    '-ti', ti, ...
    '-di', single(nan(size(ti))), ...
    '-dt', [1], ...
    '-n', 24, ...
    '-s', 100);

disp(['job ', num2str(result.job_id), ', seconds ', num2str(result.time)]);
disp(size(result.simulation));
