rng(4);
[x, y] = meshgrid(single(0:127), single(0:95));
ti1 = single(sin(x / 8) + cos(y / 11));
ti2 = single(cos((x + y) / 13) + sin(y / 7));
conditioning = single(nan(size(ti1)));
known = rand(size(ti1)) < 0.05;
conditioning(known) = ti1(known);

[result, ~] = g2s( ...
    '-a', 'as', ...
    '-ti', ti1, ti2, ...
    '-di', conditioning, ...
    '-dt', [0], ...
    '-k', 2, ...
    '-n', 8, ...
    '-s', 100);

simulation = result.simulation;
selected_ti = result.indexmap;
disp(['job ', num2str(result.job_id)]);
disp(size(simulation));
disp(size(selected_ti));
