ti = single(imread('https://raw.githubusercontent.com/GAIA-UNIL/TrainingImagesTIFF/master/stone.tiff'));

submitted = g2s( ...
    '-a', 'qs', ...
    '-submitOnly', ...
    '-ti', ti, ...
    '-di', single(nan(200, 200)), ...
    '-dt', [0], ...
    '-k', 1.2, ...
    '-n', 50, ...
    '-j', 0.5);

job_id = submitted.job_id;
status = g2s('-statusOnly', job_id);
result = g2s('-waitAndDownload', job_id);

disp(['submitted ', num2str(job_id)]);
disp(['status ', status.status, ', progress ', num2str(status.progress)]);
disp(size(result.simulation));
