ti = single(imread('https://raw.githubusercontent.com/GAIA-UNIL/TrainingImagesTIFF/master/stone.tiff'));

[result, ~] = g2s( ...
    '-a', 'qs', ...
    '-ti', ti, ...
    '-di', single(nan(200, 200)), ...
    '-dt', [0], ...
    '-k', 1.2, ...
    '-n', 50, ...
    '-j', 0.5);

simulation = result.simulation;
indexmap = result.indexmap;
disp(['job ', num2str(result.job_id), ', seconds ', num2str(result.time)]);
disp(size(simulation));
